# Generated by Django 4.2.4 on 2023-11-17 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Координаты',
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, max_length=64, null=True, verbose_name='Зима')),
                ('summer', models.CharField(blank=True, max_length=64, null=True, verbose_name='Лето')),
                ('autumn', models.CharField(blank=True, max_length=64, null=True, verbose_name='Осень')),
                ('spring', models.CharField(blank=True, max_length=64, null=True, verbose_name='Весна')),
            ],
            options={
                'verbose_name': 'Уровень сложности',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('fam', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('otc', models.CharField(max_length=64, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Турист',
            },
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField()),
                ('beauty_title', models.TextField(blank=True, null=True, verbose_name='Основное название вершины')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='Название вершины')),
                ('other_titles', models.CharField(blank=True, max_length=64, null=True, verbose_name='Другое название')),
                ('connect', models.CharField(blank=True, max_length=64, null=True, verbose_name='Связывает')),
                ('status', models.CharField(choices=[('new', 'новый'), ('pending', 'в работе'), ('accepted', 'принят'), ('rejected', 'отклонён')], default='new', max_length=64)),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('title', models.TextField(blank=True, max_length=64, null=True)),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.pereval')),
            ],
        ),
    ]
